import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

import Navigation from "./ui/navigation/Navigation";

const dm_sans = DM_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${dm_sans.className} container`}>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
